-- Telegram assistant hybrid v3.2 additions

create table if not exists assistant_local_jobs (
  job_id text primary key,
  flow_id text,
  bot_id text not null default 'tyler_durden',
  chat_id bigint not null,
  user_id bigint,
  thread_id text,
  mode text not null check (mode in ('cloud_short', 'local_heavy')),
  payload jsonb not null default '{}'::jsonb,
  status text not null check (status in ('queued', 'claimed', 'done', 'failed')),
  claimed_by text,
  attempt_count integer not null default 0,
  error text,
  completed_at timestamptz,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create index if not exists idx_assistant_local_jobs_status_created
  on assistant_local_jobs(status, created_at asc);

create index if not exists idx_assistant_local_jobs_flow_status_created
  on assistant_local_jobs(flow_id, status, created_at asc);

create index if not exists idx_assistant_local_jobs_bot_status_created
  on assistant_local_jobs(bot_id, status, created_at desc);

create table if not exists assistant_action_approvals (
  action_id text primary key,
  requested_by_bot text not null,
  action_type text not null,
  payload jsonb not null default '{}'::jsonb,
  status text not null check (status in ('draft', 'pending', 'approved', 'rejected', 'executed')),
  approved_by bigint,
  approved_at timestamptz,
  evidence text,
  created_at timestamptz not null,
  updated_at timestamptz not null
);

create index if not exists idx_assistant_action_approvals_status_created
  on assistant_action_approvals(status, created_at desc);

create index if not exists idx_assistant_action_approvals_bot_status_created
  on assistant_action_approvals(requested_by_bot, status, created_at desc);

create table if not exists assistant_cost_logs (
  id bigint generated by default as identity primary key,
  bot_id text not null,
  provider text not null,
  model text,
  tokens_in integer not null default 0,
  tokens_out integer not null default 0,
  estimated_cost numeric(12, 6) not null default 0,
  path text not null,
  created_at timestamptz not null
);

create index if not exists idx_assistant_cost_logs_created
  on assistant_cost_logs(created_at desc);

create index if not exists idx_assistant_cost_logs_bot_created
  on assistant_cost_logs(bot_id, created_at desc);
